version: '3'
services:
  web:
    build:
      context: .
      args:
        env: production
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=auth
      - MYSQL_PASSWORD=auth123456
      - MYSQL_DATABASE=auth
    volumes:
      - ~/Data/mysql:/var/lib/mysql
